name: Build Android Package

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      RUST_LOG: info
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      - name: Install cargo-ndk
        run: cargo install cargo-ndk

      - name: Perform target install
        run: rustup target add aarch64-linux-android armv7-linux-androideabi x86_64-linux-android i686-linux-android

      - name: Build android package
        run: cargo ndk -t armeabi-v7a -t arm64-v8a -t x86 -t x86_64 -o outputs build --features android --release
        working-directory: ./libDF

      - uses: actions/upload-artifact@v4
        with:
          name: android_package
          path: | 
            ./arm64-v8a/libdf.so
            ./armeabi-v7a/libdf.so
            ./x86/libdf.so
            ./x86_64/libdf.so
          working-directory: ./libDF/outputs
          
